#!/bin/bash

# Cardevia PWA Testing Script
# This script helps validate your PWA implementation

set -e

echo "🧪 Cardevia PWA Testing Suite"
echo "============================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_test() {
    echo -e "${BLUE}[TEST]${NC} $1"
}

print_pass() {
    echo -e "${GREEN}[PASS]${NC} $1"
}

print_fail() {
    echo -e "${RED}[FAIL]${NC} $1"
}

print_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

# Test 1: Check if build directory exists
print_test "Checking if PWA build exists..."
if [ -d "build/web" ]; then
    print_pass "Build directory found"
else
    print_fail "Build directory not found. Run 'flutter build web' first"
    exit 1
fi

# Test 2: Check required PWA files
print_test "Validating required PWA files..."

required_files=(
    "build/web/index.html"
    "build/web/manifest.json"
    "build/web/favicon.png"
)

for file in "${required_files[@]}"; do
    if [ -f "$file" ]; then
        print_pass "Found: $file"
    else
        print_fail "Missing: $file"
        exit 1
    fi
done

# Test 3: Check icons directory
print_test "Checking PWA icons..."
if [ -d "build/web/icons" ]; then
    icon_count=$(ls build/web/icons/*.png 2>/dev/null | wc -l)
    if [ "$icon_count" -gt 0 ]; then
        print_pass "Found $icon_count icon files"
    else
        print_fail "No icon files found in build/web/icons/"
    fi
else
    print_fail "Icons directory not found"
fi

# Test 4: Validate manifest.json
print_test "Validating manifest.json..."
if command -v node >/dev/null 2>&1; then
    if node -e "JSON.parse(require('fs').readFileSync('build/web/manifest.json', 'utf8'))" 2>/dev/null; then
        print_pass "manifest.json is valid JSON"
    else
        print_fail "manifest.json contains invalid JSON"
    fi
else
    print_warn "Node.js not found - skipping JSON validation"
fi

# Test 5: Check for service worker
print_test "Checking for service worker..."
if [ -f "build/web/flutter_service_worker.js" ]; then
    print_pass "Service worker found"
else
    print_warn "Service worker not found (will be generated by Flutter)"
fi

# Test 6: Check manifest contents
print_test "Checking manifest contents..."
if grep -q "Cardevia" build/web/manifest.json; then
    print_pass "App name properly configured"
else
    print_warn "App name might not be properly configured"
fi

if grep -q "standalone" build/web/manifest.json; then
    print_pass "Display mode set to standalone"
else
    print_fail "Display mode not set to standalone"
fi

# Test 7: Check index.html PWA meta tags
print_test "Checking PWA meta tags in index.html..."
pwa_meta_found=0

if grep -q 'rel="manifest"' build/web/index.html; then
    print_pass "Manifest link found"
    ((pwa_meta_found++))
else
    print_fail "Manifest link not found"
fi

if grep -q 'name="theme-color"' build/web/index.html; then
    print_pass "Theme color meta tag found"
    ((pwa_meta_found++))
else
    print_fail "Theme color meta tag not found"
fi

if grep -q 'apple-touch-icon' build/web/index.html; then
    print_pass "Apple touch icon found"
    ((pwa_meta_found++))
else
    print_fail "Apple touch icon not found"
fi

# Test 8: Check if service worker registration is present
print_test "Checking service worker registration..."
if grep -q "serviceWorker" build/web/index.html; then
    print_pass "Service worker registration code found"
else
    print_fail "Service worker registration code not found"
fi

# Summary
echo ""
echo "========================="
echo "🧪 PWA Test Summary"
echo "========================="

if [ "$pwa_meta_found" -eq 3 ]; then
    print_pass "All PWA meta tags present"
else
    print_warn "Some PWA meta tags missing ($pwa_meta_found/3 found)"
fi

# Recommendations
echo ""
print_info "🚀 Next Steps:"
echo "1. Deploy to HTTPS hosting (Firebase, Vercel, Netlify)"
echo "2. Test installation on Android Chrome"
echo "3. Test 'Add to Home Screen' on iOS Safari"
echo "4. Run Lighthouse audit: lighthouse https://your-domain.com --view"
echo "5. Test offline functionality"

# Local testing options
echo ""
print_info "🧪 Local Testing Options:"
echo "1. Flutter development server:"
echo "   flutter run -d chrome"
echo ""
echo "2. Static file server (Python):"
echo "   cd build/web && python -m http.server 8000"
echo "   Visit: http://localhost:8000"
echo ""
echo "3. Static file server (Node.js):"
echo "   npx http-server build/web -p 8000"
echo "   Visit: http://localhost:8000"

echo ""
print_info "📱 Mobile Testing:"
echo "1. Use Chrome DevTools device simulation"
echo "2. Test on real Android device with Chrome"
echo "3. Test on real iOS device with Safari"
echo "4. Use Lighthouse PWA audit in DevTools"

echo ""
print_pass "PWA validation completed! 🎉" 