@echo off
REM Cardevia PWA Testing Script for Windows
REM This script helps validate your PWA implementation

echo 🧪 Cardevia PWA Testing Suite
echo =============================

REM Test 1: Check if build directory exists
echo [TEST] Checking if PWA build exists...
if exist "build\web" (
    echo [PASS] Build directory found
) else (
    echo [FAIL] Build directory not found. Run 'flutter build web' first
    pause
    exit /b 1
)

REM Test 2: Check required PWA files
echo [TEST] Validating required PWA files...

if exist "build\web\index.html" (
    echo [PASS] Found: build\web\index.html
) else (
    echo [FAIL] Missing: build\web\index.html
    pause
    exit /b 1
)

if exist "build\web\manifest.json" (
    echo [PASS] Found: build\web\manifest.json
) else (
    echo [FAIL] Missing: build\web\manifest.json
    pause
    exit /b 1
)

if exist "build\web\favicon.png" (
    echo [PASS] Found: build\web\favicon.png
) else (
    echo [FAIL] Missing: build\web\favicon.png
    pause
    exit /b 1
)

REM Test 3: Check icons directory
echo [TEST] Checking PWA icons...
if exist "build\web\icons" (
    echo [PASS] Icons directory found
    dir /b "build\web\icons\*.png" >nul 2>nul
    if %ERRORLEVEL% EQU 0 (
        echo [PASS] Icon files found
    ) else (
        echo [FAIL] No PNG icon files found in build\web\icons\
    )
) else (
    echo [FAIL] Icons directory not found
)

REM Test 4: Check for service worker
echo [TEST] Checking for service worker...
if exist "build\web\flutter_service_worker.js" (
    echo [PASS] Service worker found
) else (
    echo [WARN] Service worker not found ^(will be generated by Flutter^)
)

REM Test 5: Check manifest contents
echo [TEST] Checking manifest contents...
findstr /C:"Cardevia" "build\web\manifest.json" >nul 2>nul
if %ERRORLEVEL% EQU 0 (
    echo [PASS] App name properly configured
) else (
    echo [WARN] App name might not be properly configured
)

findstr /C:"standalone" "build\web\manifest.json" >nul 2>nul
if %ERRORLEVEL% EQU 0 (
    echo [PASS] Display mode set to standalone
) else (
    echo [FAIL] Display mode not set to standalone
)

REM Test 6: Check index.html PWA meta tags
echo [TEST] Checking PWA meta tags in index.html...
set pwa_meta_found=0

findstr /C:"rel=\"manifest\"" "build\web\index.html" >nul 2>nul
if %ERRORLEVEL% EQU 0 (
    echo [PASS] Manifest link found
    set /a pwa_meta_found+=1
) else (
    echo [FAIL] Manifest link not found
)

findstr /C:"name=\"theme-color\"" "build\web\index.html" >nul 2>nul
if %ERRORLEVEL% EQU 0 (
    echo [PASS] Theme color meta tag found
    set /a pwa_meta_found+=1
) else (
    echo [FAIL] Theme color meta tag not found
)

findstr /C:"apple-touch-icon" "build\web\index.html" >nul 2>nul
if %ERRORLEVEL% EQU 0 (
    echo [PASS] Apple touch icon found
    set /a pwa_meta_found+=1
) else (
    echo [FAIL] Apple touch icon not found
)

REM Test 7: Check if service worker registration is present
echo [TEST] Checking service worker registration...
findstr /C:"serviceWorker" "build\web\index.html" >nul 2>nul
if %ERRORLEVEL% EQU 0 (
    echo [PASS] Service worker registration code found
) else (
    echo [FAIL] Service worker registration code not found
)

echo.
echo =========================
echo 🧪 PWA Test Summary
echo =========================

if %pwa_meta_found% EQU 3 (
    echo [PASS] All PWA meta tags present
) else (
    echo [WARN] Some PWA meta tags missing ^(%pwa_meta_found%/3 found^)
)

echo.
echo [INFO] 🚀 Next Steps:
echo 1. Deploy to HTTPS hosting ^(Firebase, Vercel, Netlify^)
echo 2. Test installation on Android Chrome
echo 3. Test 'Add to Home Screen' on iOS Safari
echo 4. Run Lighthouse audit: lighthouse https://your-domain.com --view
echo 5. Test offline functionality

echo.
echo [INFO] 🧪 Local Testing Options:
echo 1. Flutter development server:
echo    flutter run -d chrome
echo.
echo 2. Static file server ^(Python^):
echo    cd build\web ^&^& python -m http.server 8000
echo    Visit: http://localhost:8000
echo.
echo 3. Static file server ^(Node.js^):
echo    npx http-server build\web -p 8000
echo    Visit: http://localhost:8000

echo.
echo [INFO] 📱 Mobile Testing:
echo 1. Use Chrome DevTools device simulation
echo 2. Test on real Android device with Chrome
echo 3. Test on real iOS device with Safari
echo 4. Use Lighthouse PWA audit in DevTools

echo.
echo [PASS] PWA validation completed! 🎉

pause 